"""Add structured fields to Experience model

Revision ID: 0a7d9861680b
Revises: 132cc90be709
Create Date: 2025-08-13 09:36:49.701825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7d9861680b'
down_revision = '132cc90be709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activities', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_experience_dates'))
        batch_op.drop_index(batch_op.f('idx_experience_expert_id'))

    with op.batch_alter_table('experience_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_experience_attribute_compound'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_experience_attribute_compound'), ['attribute_id', 'experience_id'], unique=False)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_experience_expert_id'), ['expert_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_experience_dates'), ['start_date', 'end_date'], unique=False)
        batch_op.drop_column('activities')
        batch_op.drop_column('position')
        batch_op.drop_column('employer')

    # ### end Alembic commands ###
