"""add prompt versioning support

Revision ID: 132cc90be709
Revises: a74e77d46737
Create Date: 2025-08-07 15:28:04.679954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132cc90be709'
down_revision = 'a74e77d46737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns
    op.add_column('prompt', sa.Column('template_name', sa.String(length=128), nullable=True))
    op.add_column('prompt', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('prompt', sa.Column('is_active_version', sa.Boolean(), nullable=True))
    op.add_column('prompt', sa.Column('version_notes', sa.Text(), nullable=True))
    
    # Migrate existing data
    # Set template_name to current name, version_number to 1, is_active_version to is_active
    op.execute("UPDATE prompt SET template_name = name, version_number = 1, is_active_version = is_active")
    
    # Set columns as not nullable after data migration
    op.alter_column('prompt', 'template_name', nullable=False)
    op.alter_column('prompt', 'version_number', nullable=False)
    op.alter_column('prompt', 'is_active_version', nullable=False)
    
    # Remove old columns
    op.drop_constraint('uq_prompt_name', 'prompt', type_='unique')
    op.drop_column('prompt', 'name')
    op.drop_column('prompt', 'version')
    op.drop_column('prompt', 'is_active')
    
    # Add new indexes
    op.create_index('ix_prompt_template_name_version', 'prompt', ['template_name', 'version_number'])
    op.create_index('ix_prompt_template_active', 'prompt', ['template_name', 'is_active_version'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove indexes
    op.drop_index('ix_prompt_template_active', 'prompt')
    op.drop_index('ix_prompt_template_name_version', 'prompt')
    
    # Add back old columns
    op.add_column('prompt', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('prompt', sa.Column('version', sa.String(length=32), nullable=True))
    op.add_column('prompt', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Migrate data back
    op.execute("UPDATE prompt SET name = template_name, version = CAST(version_number as VARCHAR), is_active = is_active_version")
    
    # Set columns as not nullable
    op.alter_column('prompt', 'name', nullable=False)
    op.alter_column('prompt', 'version', nullable=False)
    op.alter_column('prompt', 'is_active', nullable=False)
    
    # Remove new columns
    op.drop_column('prompt', 'version_notes')
    op.drop_column('prompt', 'is_active_version')
    op.drop_column('prompt', 'version_number')
    op.drop_column('prompt', 'template_name')
    
    # Restore unique constraint
    op.create_unique_constraint('uq_prompt_name', 'prompt', ['name'])
    
    # ### end Alembic commands ###
