"""Add meta JSON field to Expert model

Revision ID: 673c881ba40b
Revises: 14586b33f817
Create Date: 2025-08-05 13:01:11.287625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673c881ba40b'
down_revision = '14586b33f817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attribute_embedding_hnsw'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
        batch_op.drop_index(batch_op.f('ix_attribute_embedding_ivfflat'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('expert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert', schema=None) as batch_op:
        batch_op.drop_column('meta')

    with op.batch_alter_table('attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attribute_embedding_ivfflat'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
        batch_op.create_index(batch_op.f('ix_attribute_embedding_hnsw'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    # ### end Alembic commands ###
