"""Add search performance indexes

Revision ID: search_indexes
Revises: 673c881ba40b
Create Date: 2025-08-05 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'search_indexes'
down_revision = '673c881ba40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add indexes for search performance
    op.create_index('idx_experience_dates', 'experience', ['start_date', 'end_date'])
    op.create_index('idx_experience_expert_id', 'experience', ['expert_id'])
    op.create_index('idx_experience_attribute_compound', 'experience_attribute', ['attribute_id', 'experience_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_experience_attribute_compound', table_name='experience_attribute')
    op.drop_index('idx_experience_expert_id', table_name='experience')
    op.drop_index('idx_experience_dates', table_name='experience')
    # ### end Alembic commands ###